server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java_code_base?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root #数据库用户名
    password: 1223yydong-MYSQL #数据库密码
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
